development:
  adapter: postgresql
  encoding: unicode
  database: bookstore_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: bookstore_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
